language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm run clean
  - npm run build
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  local_dir: public
  on:
    branch: 
      - main
      - master
