language: node_js
node_js:
  - "12"
install:
  - npm install
deploy:
  provider: script
  github_token: $GITHUB_TOKEN
  script: npm run deploy
  skip_cleanup: true
  on:
    branch: 
      - main
      - master
